app = "mariage-melissa-armonde"
primary_region = "cdg"

[build]

[env]
  DB_PATH = "/data/mariage.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "mariage_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
